### ISSUE TITLE
ar3_hardware_bringup.launch doesn't appear to exist

### ISSUE THREAD

**Issue by drmcgee** [ongdexter/ar3_core#2]
When I go to test my installation I run the command per the tutorial:
roslaunch ar3_hardware_interface ar3_hardware_bringup.launch

And I receive this error: 
RLException: [ar3_hardware_bringup.launch] is neither a launch file in package [ar3_hardware_interface] nor is [ar3_hardware_interface] a launch file name
The traceback for the exception was written to the log file

I thought perhaps it was a typo and it is supposed to be: ar3_bringup.launch instead of ar3_hardware_bringup.launch, as that file does exist, however it is a 0kb file so that fails as well.

**Comment by ongdexter** [comment]
I must have missed out this file when merging changes previously, it's just a change of file name. Thanks for catching this! I've pushed the changes so please pull the latest commit.

**Comment by drmcgee** [comment]
Perfect, thank you
