### ISSUE TITLE
Issue with teensy communication/issuing commands

### ISSUE THREAD

**Issue by JMCV22** [ongdexter/ar3_core#3]
When trying to connect with the real hardware, I'm having trouble issuing commands. If I do the normal hardware bringup is stays at the part of issuing the calibration points. If I skip this step in the launchup I can get the following results:

![Screenshot from 2021-06-10 10-48-02](https://user-images.githubusercontent.com/84532729/121565086-5f5dc880-c9d9-11eb-8529-c70406cee4d4.png)

However, when I try to move out the robot in Rviz it states that the controller couldn't respond in time, so it aborts the execution of the planned move.

I tried moving the robot using the provided teensy sketch in the ARCS software (at a different time of using the ROS package) to ensure the system was moving correctly with the default option and that was the case.

Is there something specific I could look up to find the issue here?

Also the correct port and baudrate is configured in the hardware_driver.yaml file

PD:
Thanks a lot for sharing all this development, as someone who is getting into ROS is extra helpful to better understand its systems and components.

**Comment by ongdexter** [comment]
Hi! Comms seem to be working fine and the calibration logic is handled entirely on the Teensy, so the problem is probably in that part or the hardware. Are you are able to calibrate all the joints without issues on ARCS?
